import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    // Build output and dependencies are not source. Without this, invoking
    // ESLint directly (`npx eslint .`) lints the compiled bundles in `.next/`
    // and reports ~1,850 phantom problems from generated code. `next lint`
    // ignored these implicitly, but it is deprecated and removed in Next 16,
    // so the ignores have to live in the config for the direct invocation
    // that replaces it.
    //
    // The globs are `**/`-prefixed because flat-config ignore patterns are
    // matched against the whole path from the config directory, not per
    // path segment: a bare `next-env.d.ts` only ever matches the one at the
    // repo root. Nested checkouts (see `.claude/worktrees` below) carry their
    // own `.next/` and `next-env.d.ts`, and those copies slipped through.
    ignores: [
      "**/.next/**",
      "**/node_modules/**",
      "**/out/**",
      "**/build/**",
      // Auto-generated by Next on every build; its triple-slash references
      // are the documented format and the file carries a "should not be
      // edited" notice, so it is ignored rather than rewritten to `import`.
      "**/next-env.d.ts",
      // Claude Code checks agent worktrees out *inside* the repo. Each one is
      // a complete second copy of this project on another branch, and linting
      // it here reports every one of its problems against paths that no rule
      // override matches. Each worktree lints itself from its own root.
      ".claude/worktrees/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript", "prettier"),
  {
    // The migrated animation-controller views carry blanket eslint-disable
    // directives by design (faithful re-host of the original imperative code);
    // some controllers don't trip every disabled rule, so don't flag those
    // intentional directives as "unused". See MIGRATION-NOTES.md.
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
    rules: {
      // Migrated marketing pages intentionally keep the original <img> tags and
      // hand-tuned inline styles for pixel fidelity (see MIGRATION-NOTES.md).
      "@next/next/no-img-element": "off",

      // A leading underscore is this codebase's marker for "required by the
      // signature, deliberately unused" — Server Action `(_prev, _formData)`
      // params that `useActionState` supplies, and destructuring-to-omit in the
      // smoke tests. Encoding the convention in the rule keeps the intent
      // visible at the call site instead of scattering disable comments.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
  {
    // `features/ai/pdf` builds @react-pdf/renderer documents. Its `Image` is a
    // PDF drawing primitive that never reaches the DOM and has no `alt` in its
    // API, so the HTML-oriented alt-text rule cannot apply here.
    files: ["**/features/ai/pdf/**/*.{ts,tsx}"],
    rules: {
      "jsx-a11y/alt-text": "off",
    },
  },
];

export default eslintConfig;
