import type { ReportMeta } from "@/features/ai/renderer/types";
import { formatDate } from "@/lib/format";

interface ReportFooterProps {
  meta: ReportMeta;
  disclaimer: string;
}

/**
 * ReportFooter — provenance line (REPORT-DESIGN-SYSTEM.md). Every AI report
 * states which workflow, model and prompt version produced it, plus the
 * AI-advice disclaimer.
 */
export function ReportFooter({ meta, disclaimer }: ReportFooterProps) {
  return (
    <footer className="border-t border-white/[0.06] pt-6 text-xs leading-relaxed text-muted-strong">
      <p>
        Generated by AIAutomix on {formatDate(meta.generatedAt)} ·{" "}
        {meta.workflowLabel} · model{" "}
        <span className="text-muted">{meta.model}</span> · prompt{" "}
        <span className="text-muted">{meta.promptVersion}</span>
        {meta.tokens ? (
          <>
            {" "}
            · <span className="text-muted">
              {meta.tokens.toLocaleString()}
            </span>{" "}
            tokens
          </>
        ) : null}
      </p>
      <p className="mt-1.5">{disclaimer}</p>
    </footer>
  );
}
